# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LabelConfigWnd.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(831, 652)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_save_config = QtWidgets.QPushButton(self.centralwidget)
        self.btn_save_config.setGeometry(QtCore.QRect(700, 140, 121, 61))
        self.btn_save_config.setObjectName("btn_save_config")
        self.lsv_printer_names = QtWidgets.QListView(self.centralwidget)
        self.lsv_printer_names.setGeometry(QtCore.QRect(10, 10, 181, 241))
        self.lsv_printer_names.setObjectName("lsv_printer_names")
        self.gbx_printer_info = QtWidgets.QGroupBox(self.centralwidget)
        self.gbx_printer_info.setGeometry(QtCore.QRect(200, 10, 251, 201))
        self.gbx_printer_info.setObjectName("gbx_printer_info")
        self.label = QtWidgets.QLabel(self.gbx_printer_info)
        self.label.setGeometry(QtCore.QRect(20, 40, 51, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.gbx_printer_info)
        self.label_2.setGeometry(QtCore.QRect(20, 70, 51, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.gbx_printer_info)
        self.label_3.setGeometry(QtCore.QRect(20, 90, 51, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.gbx_printer_info)
        self.label_4.setGeometry(QtCore.QRect(20, 110, 61, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.gbx_printer_info)
        self.label_5.setGeometry(QtCore.QRect(20, 130, 61, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.gbx_printer_info)
        self.label_6.setGeometry(QtCore.QRect(20, 150, 61, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.gbx_printer_info)
        self.label_7.setGeometry(QtCore.QRect(20, 170, 61, 16))
        self.label_7.setObjectName("label_7")
        self.led_printer_name = QtWidgets.QLineEdit(self.gbx_printer_info)
        self.led_printer_name.setEnabled(False)
        self.led_printer_name.setGeometry(QtCore.QRect(80, 40, 161, 20))
        self.led_printer_name.setObjectName("led_printer_name")
        self.led_printer_width = QtWidgets.QLineEdit(self.gbx_printer_info)
        self.led_printer_width.setEnabled(False)
        self.led_printer_width.setGeometry(QtCore.QRect(100, 70, 113, 20))
        self.led_printer_width.setReadOnly(True)
        self.led_printer_width.setObjectName("led_printer_width")
        self.led_printer_height = QtWidgets.QLineEdit(self.gbx_printer_info)
        self.led_printer_height.setEnabled(False)
        self.led_printer_height.setGeometry(QtCore.QRect(100, 90, 113, 20))
        self.led_printer_height.setReadOnly(True)
        self.led_printer_height.setObjectName("led_printer_height")
        self.led_printer_left_margin = QtWidgets.QLineEdit(self.gbx_printer_info)
        self.led_printer_left_margin.setEnabled(False)
        self.led_printer_left_margin.setGeometry(QtCore.QRect(100, 110, 113, 20))
        self.led_printer_left_margin.setReadOnly(True)
        self.led_printer_left_margin.setObjectName("led_printer_left_margin")
        self.led_printer_y_ppi = QtWidgets.QLineEdit(self.gbx_printer_info)
        self.led_printer_y_ppi.setEnabled(False)
        self.led_printer_y_ppi.setGeometry(QtCore.QRect(100, 170, 113, 20))
        self.led_printer_y_ppi.setReadOnly(True)
        self.led_printer_y_ppi.setObjectName("led_printer_y_ppi")
        self.led_printer_x_ppi = QtWidgets.QLineEdit(self.gbx_printer_info)
        self.led_printer_x_ppi.setEnabled(False)
        self.led_printer_x_ppi.setGeometry(QtCore.QRect(100, 150, 113, 20))
        self.led_printer_x_ppi.setReadOnly(True)
        self.led_printer_x_ppi.setObjectName("led_printer_x_ppi")
        self.led_printer_right_margin = QtWidgets.QLineEdit(self.gbx_printer_info)
        self.led_printer_right_margin.setEnabled(False)
        self.led_printer_right_margin.setGeometry(QtCore.QRect(100, 130, 113, 20))
        self.led_printer_right_margin.setReadOnly(True)
        self.led_printer_right_margin.setObjectName("led_printer_right_margin")
        self.label_8 = QtWidgets.QLabel(self.gbx_printer_info)
        self.label_8.setGeometry(QtCore.QRect(300, 130, 61, 16))
        self.label_8.setObjectName("label_8")
        self.led_printer_left_edge_2 = QtWidgets.QLineEdit(self.gbx_printer_info)
        self.led_printer_left_edge_2.setGeometry(QtCore.QRect(380, 110, 113, 20))
        self.led_printer_left_edge_2.setObjectName("led_printer_left_edge_2")
        self.led_printer_right_edge_2 = QtWidgets.QLineEdit(self.gbx_printer_info)
        self.led_printer_right_edge_2.setGeometry(QtCore.QRect(380, 130, 113, 20))
        self.led_printer_right_edge_2.setObjectName("led_printer_right_edge_2")
        self.label_9 = QtWidgets.QLabel(self.gbx_printer_info)
        self.label_9.setGeometry(QtCore.QRect(300, 150, 61, 16))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.gbx_printer_info)
        self.label_10.setGeometry(QtCore.QRect(300, 90, 51, 16))
        self.label_10.setObjectName("label_10")
        self.led_printer_height_2 = QtWidgets.QLineEdit(self.gbx_printer_info)
        self.led_printer_height_2.setGeometry(QtCore.QRect(380, 90, 113, 20))
        self.led_printer_height_2.setObjectName("led_printer_height_2")
        self.led_printer_x_ppi_2 = QtWidgets.QLineEdit(self.gbx_printer_info)
        self.led_printer_x_ppi_2.setGeometry(QtCore.QRect(380, 150, 113, 20))
        self.led_printer_x_ppi_2.setObjectName("led_printer_x_ppi_2")
        self.label_11 = QtWidgets.QLabel(self.gbx_printer_info)
        self.label_11.setGeometry(QtCore.QRect(300, 70, 51, 16))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.gbx_printer_info)
        self.label_12.setGeometry(QtCore.QRect(300, 110, 61, 16))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.gbx_printer_info)
        self.label_13.setGeometry(QtCore.QRect(300, 170, 61, 16))
        self.label_13.setObjectName("label_13")
        self.led_printer_y_ppi_2 = QtWidgets.QLineEdit(self.gbx_printer_info)
        self.led_printer_y_ppi_2.setGeometry(QtCore.QRect(380, 170, 113, 20))
        self.led_printer_y_ppi_2.setObjectName("led_printer_y_ppi_2")
        self.led_printer_width_2 = QtWidgets.QLineEdit(self.gbx_printer_info)
        self.led_printer_width_2.setGeometry(QtCore.QRect(380, 70, 113, 20))
        self.led_printer_width_2.setObjectName("led_printer_width_2")
        self.grobox_database = QtWidgets.QGroupBox(self.centralwidget)
        self.grobox_database.setGeometry(QtCore.QRect(460, 10, 211, 201))
        self.grobox_database.setObjectName("grobox_database")
        self.label_14 = QtWidgets.QLabel(self.grobox_database)
        self.label_14.setGeometry(QtCore.QRect(20, 30, 41, 16))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.grobox_database)
        self.label_15.setGeometry(QtCore.QRect(20, 50, 41, 16))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.grobox_database)
        self.label_16.setGeometry(QtCore.QRect(20, 110, 51, 16))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.grobox_database)
        self.label_17.setGeometry(QtCore.QRect(20, 70, 41, 16))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.grobox_database)
        self.label_18.setGeometry(QtCore.QRect(20, 90, 51, 16))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.grobox_database)
        self.label_19.setGeometry(QtCore.QRect(20, 130, 51, 16))
        self.label_19.setObjectName("label_19")
        self.led_db_ip = QtWidgets.QLineEdit(self.grobox_database)
        self.led_db_ip.setEnabled(False)
        self.led_db_ip.setGeometry(QtCore.QRect(80, 30, 121, 20))
        self.led_db_ip.setObjectName("led_db_ip")
        self.led_db_user = QtWidgets.QLineEdit(self.grobox_database)
        self.led_db_user.setEnabled(False)
        self.led_db_user.setGeometry(QtCore.QRect(80, 50, 121, 20))
        self.led_db_user.setObjectName("led_db_user")
        self.led_db_chk_name = QtWidgets.QLineEdit(self.grobox_database)
        self.led_db_chk_name.setEnabled(False)
        self.led_db_chk_name.setGeometry(QtCore.QRect(80, 110, 121, 20))
        self.led_db_chk_name.setObjectName("led_db_chk_name")
        self.led_db_pw = QtWidgets.QLineEdit(self.grobox_database)
        self.led_db_pw.setEnabled(False)
        self.led_db_pw.setGeometry(QtCore.QRect(80, 70, 121, 20))
        self.led_db_pw.setObjectName("led_db_pw")
        self.led_db_chk_table = QtWidgets.QLineEdit(self.grobox_database)
        self.led_db_chk_table.setEnabled(False)
        self.led_db_chk_table.setGeometry(QtCore.QRect(80, 130, 121, 20))
        self.led_db_chk_table.setObjectName("led_db_chk_table")
        self.led_db_port = QtWidgets.QLineEdit(self.grobox_database)
        self.led_db_port.setEnabled(False)
        self.led_db_port.setGeometry(QtCore.QRect(80, 90, 121, 20))
        self.led_db_port.setObjectName("led_db_port")
        self.label_41 = QtWidgets.QLabel(self.grobox_database)
        self.label_41.setGeometry(QtCore.QRect(20, 150, 51, 16))
        self.label_41.setObjectName("label_41")
        self.led_db_rec_name = QtWidgets.QLineEdit(self.grobox_database)
        self.led_db_rec_name.setEnabled(False)
        self.led_db_rec_name.setGeometry(QtCore.QRect(80, 150, 121, 20))
        self.led_db_rec_name.setObjectName("led_db_rec_name")
        self.label_42 = QtWidgets.QLabel(self.grobox_database)
        self.label_42.setGeometry(QtCore.QRect(20, 170, 51, 16))
        self.label_42.setObjectName("label_42")
        self.led_db_rec_table = QtWidgets.QLineEdit(self.grobox_database)
        self.led_db_rec_table.setEnabled(False)
        self.led_db_rec_table.setGeometry(QtCore.QRect(80, 170, 121, 20))
        self.led_db_rec_table.setObjectName("led_db_rec_table")
        self.gbx_label_setting = QtWidgets.QGroupBox(self.centralwidget)
        self.gbx_label_setting.setGeometry(QtCore.QRect(200, 300, 471, 81))
        self.gbx_label_setting.setObjectName("gbx_label_setting")
        self.label_23 = QtWidgets.QLabel(self.gbx_label_setting)
        self.label_23.setGeometry(QtCore.QRect(100, 20, 31, 16))
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.gbx_label_setting)
        self.label_24.setGeometry(QtCore.QRect(100, 60, 31, 16))
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.gbx_label_setting)
        self.label_25.setGeometry(QtCore.QRect(100, 40, 31, 16))
        self.label_25.setObjectName("label_25")
        self.ckb_use_barcode = QtWidgets.QCheckBox(self.gbx_label_setting)
        self.ckb_use_barcode.setGeometry(QtCore.QRect(10, 20, 71, 16))
        self.ckb_use_barcode.setObjectName("ckb_use_barcode")
        self.ckb_use_qrcode = QtWidgets.QCheckBox(self.gbx_label_setting)
        self.ckb_use_qrcode.setGeometry(QtCore.QRect(10, 40, 71, 16))
        self.ckb_use_qrcode.setObjectName("ckb_use_qrcode")
        self.ckb_use_hr = QtWidgets.QCheckBox(self.gbx_label_setting)
        self.ckb_use_hr.setGeometry(QtCore.QRect(10, 60, 71, 16))
        self.ckb_use_hr.setObjectName("ckb_use_hr")
        self.led_label_barcode_size = QtWidgets.QLineEdit(self.gbx_label_setting)
        self.led_label_barcode_size.setGeometry(QtCore.QRect(140, 20, 51, 20))
        self.led_label_barcode_size.setObjectName("led_label_barcode_size")
        self.led_label_hr_size = QtWidgets.QLineEdit(self.gbx_label_setting)
        self.led_label_hr_size.setGeometry(QtCore.QRect(140, 60, 51, 20))
        self.led_label_hr_size.setObjectName("led_label_hr_size")
        self.led_label_qrcode_size = QtWidgets.QLineEdit(self.gbx_label_setting)
        self.led_label_qrcode_size.setGeometry(QtCore.QRect(140, 40, 51, 20))
        self.led_label_qrcode_size.setObjectName("led_label_qrcode_size")
        self.label_28 = QtWidgets.QLabel(self.gbx_label_setting)
        self.label_28.setGeometry(QtCore.QRect(210, 40, 61, 16))
        self.label_28.setObjectName("label_28")
        self.led_label_barcode_x_offset = QtWidgets.QLineEdit(self.gbx_label_setting)
        self.led_label_barcode_x_offset.setGeometry(QtCore.QRect(280, 20, 51, 20))
        self.led_label_barcode_x_offset.setObjectName("led_label_barcode_x_offset")
        self.led_label_qrcode_x_offset = QtWidgets.QLineEdit(self.gbx_label_setting)
        self.led_label_qrcode_x_offset.setGeometry(QtCore.QRect(280, 40, 51, 20))
        self.led_label_qrcode_x_offset.setObjectName("led_label_qrcode_x_offset")
        self.led_label_hr_x_offset = QtWidgets.QLineEdit(self.gbx_label_setting)
        self.led_label_hr_x_offset.setGeometry(QtCore.QRect(280, 60, 51, 20))
        self.led_label_hr_x_offset.setObjectName("led_label_hr_x_offset")
        self.label_29 = QtWidgets.QLabel(self.gbx_label_setting)
        self.label_29.setGeometry(QtCore.QRect(210, 20, 61, 16))
        self.label_29.setObjectName("label_29")
        self.label_31 = QtWidgets.QLabel(self.gbx_label_setting)
        self.label_31.setGeometry(QtCore.QRect(210, 60, 61, 16))
        self.label_31.setObjectName("label_31")
        self.led_label_qrcode_y_offset = QtWidgets.QLineEdit(self.gbx_label_setting)
        self.led_label_qrcode_y_offset.setGeometry(QtCore.QRect(410, 40, 51, 20))
        self.led_label_qrcode_y_offset.setObjectName("led_label_qrcode_y_offset")
        self.label_33 = QtWidgets.QLabel(self.gbx_label_setting)
        self.label_33.setGeometry(QtCore.QRect(340, 40, 61, 16))
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(self.gbx_label_setting)
        self.label_34.setGeometry(QtCore.QRect(340, 20, 61, 16))
        self.label_34.setObjectName("label_34")
        self.led_label_hr_y_offset = QtWidgets.QLineEdit(self.gbx_label_setting)
        self.led_label_hr_y_offset.setGeometry(QtCore.QRect(410, 60, 51, 20))
        self.led_label_hr_y_offset.setObjectName("led_label_hr_y_offset")
        self.label_37 = QtWidgets.QLabel(self.gbx_label_setting)
        self.label_37.setGeometry(QtCore.QRect(340, 60, 61, 16))
        self.label_37.setObjectName("label_37")
        self.led_label_barcode_y_offset = QtWidgets.QLineEdit(self.gbx_label_setting)
        self.led_label_barcode_y_offset.setGeometry(QtCore.QRect(410, 20, 51, 20))
        self.led_label_barcode_y_offset.setObjectName("led_label_barcode_y_offset")
        self.label_23.raise_()
        self.label_24.raise_()
        self.label_25.raise_()
        self.ckb_use_barcode.raise_()
        self.ckb_use_qrcode.raise_()
        self.ckb_use_hr.raise_()
        self.led_label_barcode_size.raise_()
        self.led_label_hr_size.raise_()
        self.led_label_qrcode_size.raise_()
        self.led_label_barcode_x_offset.raise_()
        self.led_label_qrcode_x_offset.raise_()
        self.led_label_hr_x_offset.raise_()
        self.label_29.raise_()
        self.label_31.raise_()
        self.led_label_qrcode_y_offset.raise_()
        self.label_33.raise_()
        self.label_34.raise_()
        self.led_label_hr_y_offset.raise_()
        self.label_37.raise_()
        self.led_label_barcode_y_offset.raise_()
        self.label_28.raise_()
        self.btn_quit_config = QtWidgets.QPushButton(self.centralwidget)
        self.btn_quit_config.setGeometry(QtCore.QRect(700, 270, 121, 61))
        self.btn_quit_config.setObjectName("btn_quit_config")
        self.gbx_add_label = QtWidgets.QGroupBox(self.centralwidget)
        self.gbx_add_label.setGeometry(QtCore.QRect(200, 390, 471, 151))
        self.gbx_add_label.setObjectName("gbx_add_label")
        self.led_add_label_x_offset = QtWidgets.QLineEdit(self.gbx_add_label)
        self.led_add_label_x_offset.setGeometry(QtCore.QRect(80, 40, 51, 20))
        self.led_add_label_x_offset.setObjectName("led_add_label_x_offset")
        self.label_45 = QtWidgets.QLabel(self.gbx_add_label)
        self.label_45.setGeometry(QtCore.QRect(20, 40, 61, 16))
        self.label_45.setObjectName("label_45")
        self.label_46 = QtWidgets.QLabel(self.gbx_add_label)
        self.label_46.setGeometry(QtCore.QRect(220, 40, 61, 20))
        self.label_46.setObjectName("label_46")
        self.led_add_label_y_offset = QtWidgets.QLineEdit(self.gbx_add_label)
        self.led_add_label_y_offset.setGeometry(QtCore.QRect(280, 40, 61, 20))
        self.led_add_label_y_offset.setObjectName("led_add_label_y_offset")
        self.label_47 = QtWidgets.QLabel(self.gbx_add_label)
        self.label_47.setGeometry(QtCore.QRect(20, 20, 61, 20))
        self.label_47.setObjectName("label_47")
        self.led_add_label_width = QtWidgets.QLineEdit(self.gbx_add_label)
        self.led_add_label_width.setGeometry(QtCore.QRect(80, 20, 51, 20))
        self.led_add_label_width.setObjectName("led_add_label_width")
        self.led_add_label_right_margin = QtWidgets.QLineEdit(self.gbx_add_label)
        self.led_add_label_right_margin.setGeometry(QtCore.QRect(280, 60, 61, 20))
        self.led_add_label_right_margin.setObjectName("led_add_label_right_margin")
        self.label_50 = QtWidgets.QLabel(self.gbx_add_label)
        self.label_50.setGeometry(QtCore.QRect(20, 60, 61, 16))
        self.label_50.setObjectName("label_50")
        self.led_add_label_left_margin = QtWidgets.QLineEdit(self.gbx_add_label)
        self.led_add_label_left_margin.setGeometry(QtCore.QRect(80, 60, 51, 20))
        self.led_add_label_left_margin.setObjectName("led_add_label_left_margin")
        self.label_51 = QtWidgets.QLabel(self.gbx_add_label)
        self.label_51.setGeometry(QtCore.QRect(220, 60, 61, 20))
        self.label_51.setObjectName("label_51")
        self.label_48 = QtWidgets.QLabel(self.gbx_add_label)
        self.label_48.setGeometry(QtCore.QRect(220, 20, 51, 16))
        self.label_48.setObjectName("label_48")
        self.led_add_label_height = QtWidgets.QLineEdit(self.gbx_add_label)
        self.led_add_label_height.setGeometry(QtCore.QRect(280, 20, 61, 20))
        self.led_add_label_height.setObjectName("led_add_label_height")
        self.ckb_change_default = QtWidgets.QCheckBox(self.centralwidget)
        self.ckb_change_default.setGeometry(QtCore.QRect(700, 200, 111, 31))
        self.ckb_change_default.setObjectName("ckb_change_default")
        self.lsv_label_size = QtWidgets.QListView(self.centralwidget)
        self.lsv_label_size.setGeometry(QtCore.QRect(10, 260, 181, 281))
        self.lsv_label_size.setObjectName("lsv_label_size")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(200, 220, 471, 51))
        self.groupBox.setObjectName("groupBox")
        self.label_height = QtWidgets.QLabel(self.groupBox)
        self.label_height.setGeometry(QtCore.QRect(350, 20, 51, 16))
        self.label_height.setObjectName("label_height")
        self.led_label_height = QtWidgets.QLineEdit(self.groupBox)
        self.led_label_height.setEnabled(False)
        self.led_label_height.setGeometry(QtCore.QRect(400, 20, 51, 20))
        self.led_label_height.setObjectName("led_label_height")
        self.label_26 = QtWidgets.QLabel(self.groupBox)
        self.label_26.setGeometry(QtCore.QRect(210, 20, 51, 16))
        self.label_26.setObjectName("label_26")
        self.led_label_model = QtWidgets.QLineEdit(self.groupBox)
        self.led_label_model.setEnabled(False)
        self.led_label_model.setGeometry(QtCore.QRect(40, 20, 151, 20))
        self.led_label_model.setReadOnly(True)
        self.led_label_model.setObjectName("led_label_model")
        self.label_20 = QtWidgets.QLabel(self.groupBox)
        self.label_20.setGeometry(QtCore.QRect(10, 20, 31, 16))
        self.label_20.setObjectName("label_20")
        self.led_label_width = QtWidgets.QLineEdit(self.groupBox)
        self.led_label_width.setEnabled(False)
        self.led_label_width.setGeometry(QtCore.QRect(260, 20, 51, 20))
        self.led_label_width.setObjectName("led_label_width")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 831, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "产品标签打印设置"))
        self.btn_save_config.setText(_translate("MainWindow", "保存"))
        self.gbx_printer_info.setTitle(_translate("MainWindow", "打印机信息"))
        self.label.setText(_translate("MainWindow", "打印机名"))
        self.label_2.setText(_translate("MainWindow", "宽度(mm)"))
        self.label_3.setText(_translate("MainWindow", "高度(mm)"))
        self.label_4.setText(_translate("MainWindow", "左边缘(mm)"))
        self.label_5.setText(_translate("MainWindow", "右边缘(mm)"))
        self.label_6.setText(_translate("MainWindow", "X_PPI(mm)"))
        self.label_7.setText(_translate("MainWindow", "Y_PPI(mm)"))
        self.label_8.setText(_translate("MainWindow", "右边缘(mm)"))
        self.label_9.setText(_translate("MainWindow", "X_PPI(mm)"))
        self.label_10.setText(_translate("MainWindow", "高度(mm)"))
        self.label_11.setText(_translate("MainWindow", "宽度(mm)"))
        self.label_12.setText(_translate("MainWindow", "左边缘(mm)"))
        self.label_13.setText(_translate("MainWindow", "Y_PPI(mm)"))
        self.grobox_database.setTitle(_translate("MainWindow", "数据库信息"))
        self.label_14.setText(_translate("MainWindow", "主机IP"))
        self.label_15.setText(_translate("MainWindow", "用户名"))
        self.label_16.setText(_translate("MainWindow", "结果库"))
        self.label_17.setText(_translate("MainWindow", "密码"))
        self.label_18.setText(_translate("MainWindow", "端口"))
        self.label_19.setText(_translate("MainWindow", "结果表"))
        self.label_41.setText(_translate("MainWindow", "参数库"))
        self.label_42.setText(_translate("MainWindow", "参数表"))
        self.gbx_label_setting.setTitle(_translate("MainWindow", "标签设置"))
        self.label_23.setText(_translate("MainWindow", "大小"))
        self.label_24.setText(_translate("MainWindow", "大小"))
        self.label_25.setText(_translate("MainWindow", "大小"))
        self.ckb_use_barcode.setText(_translate("MainWindow", "条形码"))
        self.ckb_use_qrcode.setText(_translate("MainWindow", "二维码"))
        self.ckb_use_hr.setText(_translate("MainWindow", "明码"))
        self.label_28.setText(_translate("MainWindow", "X偏移(mm)"))
        self.label_29.setText(_translate("MainWindow", "X偏移(mm)"))
        self.label_31.setText(_translate("MainWindow", "X偏移(mm)"))
        self.label_33.setText(_translate("MainWindow", "Y偏移(mm)"))
        self.label_34.setText(_translate("MainWindow", "Y偏移(mm)"))
        self.label_37.setText(_translate("MainWindow", "Y偏移(mm)"))
        self.btn_quit_config.setText(_translate("MainWindow", "退出"))
        self.gbx_add_label.setTitle(_translate("MainWindow", "打印设置"))
        self.label_45.setText(_translate("MainWindow", "X偏移(mm)"))
        self.label_46.setText(_translate("MainWindow", "Y偏移(mm)"))
        self.label_47.setText(_translate("MainWindow", "宽度(mm)"))
        self.label_50.setText(_translate("MainWindow", "<html><head/><body><p>左边缘</p></body></html>"))
        self.label_51.setText(_translate("MainWindow", "右边缘"))
        self.label_48.setText(_translate("MainWindow", "高度(mm)"))
        self.ckb_change_default.setText(_translate("MainWindow", "保存此配置\n"
"为默认配置"))
        self.groupBox.setTitle(_translate("MainWindow", "标签信息"))
        self.label_height.setText(_translate("MainWindow", "高度(mm)"))
        self.label_26.setText(_translate("MainWindow", "宽度(mm)"))
        self.label_20.setText(_translate("MainWindow", "型号"))

