# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'print_sn.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.setEnabled(True)
        MainWindow.resize(885, 639)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gbx_label_view = QtWidgets.QGroupBox(self.centralwidget)
        self.gbx_label_view.setGeometry(QtCore.QRect(0, 40, 621, 371))
        self.gbx_label_view.setObjectName("gbx_label_view")
        self.gph_view_label = QtWidgets.QGraphicsView(self.gbx_label_view)
        self.gph_view_label.setGeometry(QtCore.QRect(10, 20, 571, 351))
        self.gph_view_label.setMouseTracking(True)
        self.gph_view_label.setAutoFillBackground(False)
        self.gph_view_label.setObjectName("gph_view_label")
        self.slider_pre_view = QtWidgets.QSlider(self.gbx_label_view)
        self.slider_pre_view.setGeometry(QtCore.QRect(590, 30, 22, 321))
        self.slider_pre_view.setMinimum(1)
        self.slider_pre_view.setMaximum(40)
        self.slider_pre_view.setPageStep(1)
        self.slider_pre_view.setProperty("value", 7)
        self.slider_pre_view.setSliderPosition(7)
        self.slider_pre_view.setOrientation(QtCore.Qt.Vertical)
        self.slider_pre_view.setObjectName("slider_pre_view")
        self.gbx_log = QtWidgets.QGroupBox(self.centralwidget)
        self.gbx_log.setGeometry(QtCore.QRect(10, 440, 611, 161))
        self.gbx_log.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.gbx_log.setObjectName("gbx_log")
        self.ted_log = QtWidgets.QTextEdit(self.gbx_log)
        self.ted_log.setGeometry(QtCore.QRect(10, 20, 561, 151))
        self.ted_log.setInputMethodHints(QtCore.Qt.ImhNone)
        self.ted_log.setLineWidth(1)
        self.ted_log.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.ted_log.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.ted_log.setReadOnly(True)
        self.ted_log.setObjectName("ted_log")
        self.btn_start = QtWidgets.QPushButton(self.centralwidget)
        self.btn_start.setGeometry(QtCore.QRect(690, 460, 93, 41))
        self.btn_start.setObjectName("btn_start")
        self.label_products = QtWidgets.QLabel(self.centralwidget)
        self.label_products.setGeometry(QtCore.QRect(0, 0, 391, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_products.setFont(font)
        self.label_products.setStyleSheet("color: rgb(0, 0, 255);")
        self.label_products.setText("")
        self.label_products.setAlignment(QtCore.Qt.AlignCenter)
        self.label_products.setObjectName("label_products")
        self.label_label = QtWidgets.QLabel(self.centralwidget)
        self.label_label.setGeometry(QtCore.QRect(420, 0, 101, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.label_label.setFont(font)
        self.label_label.setText("")
        self.label_label.setObjectName("label_label")
        self.label_sortSN = QtWidgets.QLabel(self.centralwidget)
        self.label_sortSN.setGeometry(QtCore.QRect(530, 0, 91, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.label_sortSN.setFont(font)
        self.label_sortSN.setStyleSheet("color: rgb(0, 0, 255);")
        self.label_sortSN.setText("")
        self.label_sortSN.setObjectName("label_sortSN")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(650, 210, 41, 16))
        self.label_5.setObjectName("label_5")
        self.lineEdit_output = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_output.setGeometry(QtCore.QRect(710, 210, 111, 20))
        self.lineEdit_output.setObjectName("lineEdit_output")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(640, 250, 51, 16))
        self.label_4.setObjectName("label_4")
        self.lineEdit_materialNum = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_materialNum.setGeometry(QtCore.QRect(710, 250, 111, 20))
        self.lineEdit_materialNum.setObjectName("lineEdit_materialNum")
        self.btn_reprint = QtWidgets.QPushButton(self.centralwidget)
        self.btn_reprint.setEnabled(True)
        self.btn_reprint.setGeometry(QtCore.QRect(690, 500, 91, 41))
        self.btn_reprint.setObjectName("btn_reprint")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(650, 170, 41, 16))
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_2.setObjectName("label_2")
        self.comboBox_Lines = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_Lines.setGeometry(QtCore.QRect(710, 170, 111, 20))
        self.comboBox_Lines.setObjectName("comboBox_Lines")
        self.checkBox_preScan = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_preScan.setGeometry(QtCore.QRect(790, 510, 71, 16))
        self.checkBox_preScan.setChecked(True)
        self.checkBox_preScan.setObjectName("checkBox_preScan")
        self.pgb_print_progress = QtWidgets.QProgressBar(self.centralwidget)
        self.pgb_print_progress.setGeometry(QtCore.QRect(10, 410, 611, 20))
        self.pgb_print_progress.setProperty("value", 0)
        self.pgb_print_progress.setObjectName("pgb_print_progress")
        self.btn_test_printer = QtWidgets.QPushButton(self.centralwidget)
        self.btn_test_printer.setGeometry(QtCore.QRect(780, 460, 93, 41))
        self.btn_test_printer.setObjectName("btn_test_printer")
        self.label_2.raise_()
        self.comboBox_Lines.raise_()
        self.gbx_label_view.raise_()
        self.gbx_log.raise_()
        self.btn_start.raise_()
        self.label_products.raise_()
        self.label_label.raise_()
        self.label_sortSN.raise_()
        self.label_5.raise_()
        self.lineEdit_output.raise_()
        self.label_4.raise_()
        self.lineEdit_materialNum.raise_()
        self.btn_reprint.raise_()
        self.checkBox_preScan.raise_()
        self.pgb_print_progress.raise_()
        self.btn_test_printer.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 885, 23))
        self.menubar.setObjectName("menubar")
        self.m_menu = QtWidgets.QMenu(self.menubar)
        self.m_menu.setObjectName("m_menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.m_menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "奥比产品SN标签打印工具--v2.0.1.2"))
        self.gbx_label_view.setTitle(_translate("MainWindow", "标签预览"))
        self.gbx_log.setTitle(_translate("MainWindow", "日志"))
        self.btn_start.setText(_translate("MainWindow", "开始"))
        self.label_5.setText(_translate("MainWindow", "产量"))
        self.label_4.setText(_translate("MainWindow", "物料号"))
        self.btn_reprint.setText(_translate("MainWindow", "接着打印"))
        self.label_2.setText(_translate("MainWindow", "线别"))
        self.checkBox_preScan.setText(_translate("MainWindow", "预览"))
        self.btn_test_printer.setText(_translate("MainWindow", "测试打印"))
        self.m_menu.setTitle(_translate("MainWindow", "选择产品"))

